blank_issues_enabled: false
contact_links:
  - name: Discord Server
    url: https://discord.gg/
    about: Join our Discord server for support and updates.
  - name: Telegram group
    url: https://telegram.me/saikou_app
    about: Join our Telegram group for releases and updates.
